version: 2

jobs:
  sonar-pr:
    docker:
      - image: circleci/openjdk:11
    steps:
    - checkout
    - restore_cache:
        key: jdp-sonar-pr-{{ checksum "pom.xml" }}
    - run: |
        if [ -n "${CIRCLE_PR_NUMBER}" ]; then
          MAVEN_OPTS="-Xmx3000m" ./mvnw -B clean verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar \
             -Dsonar.pullrequest.key=${CIRCLE_PR_NUMBER} \
             -Dsonar.pullrequest.branch=${CIRCLE_BRANCH} \
             -Dsonar.pullrequest.base=master
        else
          echo "No Sonar PR analysis as this is not a pull request"
        fi
    - save_cache:
        key: jdp-sonar-pr-{{ checksum "pom.xml" }}
        paths:
        - ~/.m2

workflows:
  version: 2
  all:
    jobs:
    - sonar-pr
